### ISSUE TITLE
Swift 4

### ISSUE THREAD

**Issue by TomWFox** [welbesw/easypost-swift#2]
Are you planning to update this to Swift 4? I may be able to update it and submit a pull request if you are unable to but I am by no means a Swift expert. Thanks 😃

**Comment by welbesw** [comment]
It was just updated to support Swift 4 and Xcode 9.  Please use tag 1.1.1 of the cocoapod. Hope that works!

**Comment by TomWFox** [comment]
Brilliant, thank you 😄
