### ISSUE TITLE
Customs

### ISSUE THREAD

**Issue by sachinvas** [welbesw/easypost-swift#6]
Hi @welbesw,

I have submitted a pull request to include the `Customs` information when creating the shipment request for international shipments. Can you please review and merge?

**Comment by sachinvas** [comment]
Hi @welbesw and @Tom-Fox1, 

Is there any reason for not merging or any contribution document I should follow?

**Comment by TomWFox** [comment]
I'm sorry, I don't know. I don't have write access so I can't really help, it seems that @welbesw is inactive.

@welbesw could you please take a look at #4.

**Comment by welbesw** [comment]
Thanks for the contribution @sachinvas .  The customs branch has now been merged into master and the cocoapod has been updated to the latest.

**Comment by sachinvas** [comment]
@welbesw thanks for accepting the pull request.
